import './globals.css';
import { Inter } from 'next/font/google';
import Header from '@/app/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Home - LimaPuluh',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="flex min-h-screen flex-col px-8 md:px-28">
					<Header />
					{children}
				</main>
			</body>
		</html>
	);
}
